# Generated by Django 4.0.5 on 2022-07-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_promocion_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='id_promocion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
