# Generated by Django 4.0.6 on 2022-07-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='suscrito',
            field=models.BooleanField(default=False),
        ),
    ]
