# Generated by Django 4.0.6 on 2022-07-05 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_usuario_suscrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id_suscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('monto_mensual', models.IntegerField()),
                ('fecha', models.DateTimeField(default=datetime.datetime(2022, 7, 5, 17, 9, 24, 210067))),
            ],
        ),
    ]
