# Generated by Django 4.0.6 on 2022-07-07 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_suscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.EmailField(max_length=254)),
                ('subtotal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carrito', models.IntegerField()),
                ('id_producto', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('subtotal_producto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.EmailField(max_length=254)),
                ('fecha', models.DateField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 23, 12, 8, 343483)),
        ),
    ]
