# Generated by Django 4.0.6 on 2022-07-07 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_carrito_carritoitem_venta_alter_suscripcion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 23, 16, 58, 699208)),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
    ]
