# Generated by Django 4.0.6 on 2022-07-07 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_carrito_username_alter_suscripcion_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 0, 47, 50, 566714)),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.FloatField(),
        ),
    ]
