# Generated by Django 4.0.6 on 2022-07-07 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_suscripcion_fecha_alter_venta_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 0, 51, 34, 31147)),
        ),
    ]
