# Generated by Django 4.0.6 on 2022-07-08 01:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_suscripcion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha_entrega',
            field=models.DateField(default=datetime.datetime(2022, 7, 14, 21, 56, 39, 394505)),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 21, 56, 39, 393508)),
        ),
    ]
